# Generated by Django 4.2.16 on 2025-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(default='No.123, bus stop, Kano State.', max_length=100),
        ),
    ]
