# Generated by Django 4.2.23 on 2025-06-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_braintree_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.CharField(default="080xxxxxxx", max_length=11),
        ),
    ]
