# Generated by Django 4.2.16 on 2025-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_price', models.IntegerField()),
                ('crop_desc', models.TextField()),
                ('crop_img', models.ImageField(upload_to='img/products_img')),
            ],
        ),
    ]
