# Generated by Django 4.2.16 on 2025-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
