# Generated by Django 4.2.16 on 2025-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_withdrawalrequest_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='withdrawal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
